### PR TITLE
Big metric thread can be wrong

### PR DESCRIPTION
**Pull request by hugosman65**
I found a bug and it took me an hour find out what is wrong, i wanted to share it with you.
If you use metric thread , you might see that above a certain value, it is completly wrong.
For my case, the pitch was ok below 1,5mm per rear. Above 1,75mm, it was very low and completly wrong.
The problem comes from the variable HMM_NUMERATOR and HMM_DENOMINATOR declared as 32bits integer. Those number are beyond 2^32, for my case after1,75mm per rear (175*10*8*1600*10*20).
The solution is very easy, declare this variable as 64bits, it works like a charm.

#if defined(LEADSCREW_TPI)
#define HMM_NUMERATOR(hmm) ((Uint64)hmm*10*LEADSCREW_TPI*STEPPER_RESOLUTION*STEPPER_MICROSTEPS)
#define HMM_DENOMINATOR(hmm) ((Uint64)ENCODER_RESOLUTION*254*100)
#endif
#if defined(LEADSCREW_HMM)
#define HMM_NUMERATOR(hmm) ((Uint64)hmm*STEPPER_RESOLUTION*STEPPER_MICROSTEPS)
#define HMM_DENOMINATOR(hmm) ((Uint64)ENCODER_RESOLUTION*LEADSCREW_HMM)
#endif

I guess you do not see this bug with TPI or metric feeding because figures are smaller.
By the way, thanks a lot for your els, i transformed a very old atlas lathe to a fantastic threading machine.
Your explanations are always so cleared, it is a pleasure to watch your videos.
But i plan to develop it on an arduino because some friends of mine want the same and it is too complicated and expensive with TI board.

### CODE REVIEW

**Comment by JonWoellhaf** [comment]
Thanks for posting this!

**Comment by clough42** [comment]
@hugosman65 I'm a little confused by the large number of files in the commit.

What are the actual required changes?  Just the cast in the macros?  I assume you also changed the data type in the FEED_THREAD structure?

**Comment by clough42** [comment]
Hmm...this looks like maybe the the pull request is erroneously referencing a couple of unrelated branches...

**Comment by clough42** [comment]
I fiddled with this a bit, and this change doubles the time spent in the interrupt routine from 1.4uS to about 2.8uS.  That's not ideal.  I wonder if there's a way to precompute.

**Comment by clough42** [comment]
Sorry...false alarm.  I was seeing a debug/release optimization difference.

**Comment by clough42** [comment]
This is now merged into the dev branch.

**Comment by clough42** [comment]
I just put a few more changes into the dev branch that I hope will address most of the reliability issues people have been seeing.  Here are the changes:

- Fix overflow that caused problems with large metric threads (thanks @hugosman95)
- Slow down the SPI bus from 250Kbps to 98Kbps
- Increase SPI timing delays slightly
- Aggressively filter bad key reads:
  - Require multiple, identical, consecutive reads before acting
  - Validate that only one key is pressed at a time (thanks @ngreenou)
  - Require all keys to be released between key presses
- Do not allow changes to mode or direction while the machine is in motion (thanks @C4fishfood)
- Add configuration option to ignore all keypresses when the machine is in motion (thanks @C4fishfood)

You can either pull the dev branch or you can download a zip of the code with these fixes here:

  https://github.com/clough42/electronic-leadscrew/archive/dev.zip

If you try this, please report back.  I would like some positive feedback before I mark it as a global release.

**Comment by clough42** [comment]
I just made a new release (v1.2.00) that should fix this issue.  Please try it and let me know if it helps.

https://github.com/clough42/electronic-leadscrew/releases/tag/v1.2.00

**Comment by Vrossi050** [comment]
On the last two bullet points, won't that disable changing feed rate while in motion (I love that feature)?

**Comment by clough42** [comment]
@Vrossi050 yes and/or no.

The default mode is to lock only the mode and direction switches.  In this configuration, you can still press the up and down buttons while the spindle is turning.

If you uncomment the additional setting in Configuration.h, you can disable the up and down buttons, but this is not the default.

Do you have a use case for changing the mode or direction while the spindle is turning?  I couldn't think of one and disabling the mode changes solves a whole bunch of problems with sudden speed/direction changes and servo faults.

**Comment by Vrossi050** [comment]
The up and down button is all I am concerned about. I use for feed speed changes on the fly. I don't change modes or directions while the motion.

**Comment by clough42** [comment]
Closing this, since the feature has been merged and released.

**Pull request closed without merging**
